language: python
python:
  - "3.4"
  - "3.3"
  - "2.7"

install: python setup.py install

script:  python -m traad.test.unittests
script:  python traad/test/acceptance/long_running.py
script:  python -m traad.test.acceptance.json_api